export const TASKS = [
  'Nil',
  'Arbitration/Litigation',
  'Basic Research',
  'Client Consultants Meeting',
  'Contract Admin',
  'Design',
  'Discussion',
  'General Admin',
  'Inspection and Handover',
  'Interview Session',
  'Meeting',
  'Others',
  'Presentation',
  'Production',
  'Project Co-ordination',
  'Seminar/Course',
  'Senarai Semak Pelan Bangunan',
  'Site Inspection',
  'Site Meeting',
  'Site Support',
  'Site Visit',
  'Submission',
  'Training',
  'Workshop',
]
